### ISSUE TITLE
Missing requirement

### ISSUE THREAD

**Issue by FedeClaudi** [adamltyson/fancylog#3]
Hey, 

I think you need to have `packaging` in your requirements. 
If I just do `pip install fancylog` I get this error:
```
ModuleNotFoundError: No module named 'packaging'
```
which is fixed with `pip install packaging`

**Comment by adamltyson** [comment]
Weird, I've never seen this. What python distribution are you using?

I can add `packaging` as a requirement, but a quick google suggests that it might be a pip issue. Can you reproduce (in a new conda env etc), and then try `pip install pip --upgrade` to see if that fixes it?

**Comment by FedeClaudi** [comment]
The same happened in a vanilla environment with pip `20.0.2`.

**Comment by adamltyson** [comment]
Added to requirements in ed9ad5cafa66783ade37eaefb4762009c5ce86df. Could you test if you get a minute?
