### ISSUE TITLE
no timestamp in file name

### ISSUE THREAD

**Issue by FedeClaudi** [adamltyson/fancylog#5]
Hi Adam, 

Maybe I missed it, but is there a way to avoid having the time stamp in the `.log` file?
I'm saving the log into a folder which already has the time stamp info in the path and was hoping to keep the `log` file short... 

Thanks :)

**Comment by adamltyson** [comment]
I don't think so, but it could easily be optional.

**Comment by adamltyson** [comment]
Hey,

I've added this (20d774d894aac313d92ce12f33be60413ae6d7de), and it's in version `0.2.0`. Usage is pretty straightforward:
```python
    fancylog.start_logging(
        directory,
        package,
        variables=[args],
        timestamp=False
    )

**Comment by FedeClaudi** [comment]
Thanks!
